"""empty message

Revision ID: 3b35bd28e520
Revises: b05a587d6367
Create Date: 2016-05-15 15:09:18.309314

"""

# revision identifiers, used by Alembic.
revision = '3b35bd28e520'
down_revision = 'b05a587d6367'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('locktime', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'locktime')
    ### end Alembic commands ###
